---
version: 2.1

executors:
  node-lts:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
        keys: 
          - v1-dependencies-{{checksum "package.json"}}
          - v1-dependencies-

jobs:
  build: 
    executor: node-lts
    steps:
    - setup
    - run:
      commands: |
        yarn type-check
        yarn lint
        yarn coverage
    - store_artifacts:
      path: ~/repo/coverage

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
        require:
          - build